services:
  postgres:
    container_name: sevsu_ud
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: sevsu_ud_online_course
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: